#pragma once
#include <EEPROM.h>

#define EEPROM_SIZE 512

#define BAK_ADDRESS_WIFI_SSID           0
#define BAK_ADDRESS_WIFI_KEY            (BAK_ADDRESS_WIFI_SSID + 32)
#define BAK_ADDRESS_WEB_HOST            (BAK_ADDRESS_WIFI_KEY+64)
#define BAK_ADDRESS_WIFI_MODE       (BAK_ADDRESS_WEB_HOST+64)
#define BAK_ADDRESS_WIFI_VALID      (BAK_ADDRESS_WIFI_MODE + 16)
#define BAK_ADDRESS_MODULE_ID       (BAK_ADDRESS_WIFI_VALID + 16)
#define BAK_ADDRESS_RESERVE1        (BAK_ADDRESS_MODULE_ID + 32)
#define BAK_ADDRESS_RESERVE2        (BAK_ADDRESS_RESERVE1 + 16)
#define BAK_ADDRESS_RESERVE3        (BAK_ADDRESS_RESERVE2 + 96)
#define BAK_ADDRESS_RESERVE4        (BAK_ADDRESS_RESERVE3 + 16)
#define BAK_ADDRESS_MANUAL_IP_FLAG  (BAK_ADDRESS_RESERVE4 + 1)
#define BAK_ADDRESS_MANUAL_IP           (BAK_ADDRESS_MANUAL_IP_FLAG + 1)
#define BAK_ADDRESS_MANUAL_MASK     (BAK_ADDRESS_MANUAL_IP + 4)
#define BAK_ADDRESS_MANUAL_GATEWAY  (BAK_ADDRESS_MANUAL_MASK + 4)
#define BAK_ADDRESS_MANUAL_DNS      (BAK_ADDRESS_MANUAL_GATEWAY + 4)

extern bool EEPROM_WriteString (int pos, const char * byte_buffer, uint8_t max);
